name: Deploy Documentation

on:
  push:
    branches:
      - main  # Set this to your default branch
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install .
      
      - name: Generate API documentation
        run: |
          pdoc --html --output-dir docs/api floppy
      
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force 