import json
import os
import re
from copy import deepcopy
from pathlib import Path
from typing import Iterable, Mapping, Optional, Union

import numpy as np
import pandas as pd
import torch
from data_utils import load_eval_stats
from numpy.typing import ArrayLike
from scipy.spatial.transform import Rotation as R

# Path settings - mirrors those in configs/common.py
DMC_ROOT_DIR = Path(os.environ.get("DMC_ROOT_DIR", "~/tbp/results/dmc")).expanduser()
DMC_PRETRAIN_DIR = DMC_ROOT_DIR / "pretrained_models"
DMC_RESULTS_DIR = DMC_ROOT_DIR / "results"
VISUALIZATION_RESULTS_DIR = DMC_ROOT_DIR / "visualizations"

# Root directory for output generated by figure scripts.
DMC_ANALYSIS_DIR = Path(
    os.environ.get("DMC_ANALYSIS_DIR", "~/tbp/results/dmc_analysis")
).expanduser()
DMC_ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)


dataframes = [
    load_eval_stats("dist_agent_1lm"),
    load_eval_stats("dist_agent_1lm_noise"),
    load_eval_stats("dist_agent_1lm_randrot_all"),
    load_eval_stats("dist_agent_1lm_randrot_all_noise"),
]

match = ["correct"]
a = dataframes[0]
